name: Python CI

on: [push]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install pytest
      run: pip install pytest
    
    - name: Run tests
      run: pytest