name: Python Check

on: [push]  

jobs:
  setup:
    runs-on: macos-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Check Python version
      run: python --version  